Fixe underflow uint256 sub
smartcontractkit/chainlink-starknet pull request #146
Opened 2022-10-04 09:10 UTC by qperrot

2022-10-04 17:41 UTC, archseer commented
`link_available_for_payment` should also be fixed?

2022-10-05 07:37 UTC, qperrot commented
>

2022-10-07 11:40 UTC, krebernisak requested changes
For `` fn, if the result is expected to be negative number in situations of contract debt, then there is no issue but this should be properly documented:
> However, since the felt type in Cairo is not signed, whoever calls this function will have to interpret the result as the correct negative value.

@qperrot please add in-line docs to the function, and also the line where the subtraction happens so we explain what's expected here.

2022-10-07 11:40 UTC, krebernisak commented on contracts/src/chainlink/cairo/ocr2/aggregator.cairo
> +    with_attr error_message("Total amount due exceeds the balance"):
We should prefix all error messages with contract/namespace like so:

```suggestion
    with_attr error_message("Aggregator: Total amount due exceeds the balance"):
```

2022-10-07 11:40 UTC, krebernisak commented on contracts/src/chainlink/cairo/ocr2/aggregator.cairo
> +    with_attr error_message("Total amount due exceeds the balance"):
No need to do in this PR. I've created a separate issue for it: https://github.com/smartcontractkit/chainlink-starknet/issues/156

2022-10-11 07:05 UTC, krebernisak approved these changes

2022-10-11 07:05 UTC, merged