Restructure of integration-tests
smartcontractkit/chainlink-starknet pull request #205
Opened 2023-01-23 12:22 UTC by smickovskid

- Removed ginkgo
- Moved to TOML
- Refactored structure

2023-02-28 15:00 UTC, sdrug submitted a review, later dismissed
LGTM! Let's also update the README since ginkgo suite is not used anymore.

2023-02-28 16:11 UTC, tateexon submitted a review, later dismissed

2023-02-28 16:18 UTC, aalu1418 requested changes
🎉 

just one small change to keep the `go.mod` a little cleaner :)

2023-02-28 16:18 UTC, aalu1418 commented on .tool-versions
> -ginkgo 2.1.3
🎉

2023-02-28 16:18 UTC, aalu1418 commented on integration-tests/go.mod
>  require (
can we combine the two `// indirect` sections to keep it cleaner? (not sure why go decides to split things)

2023-03-01 12:59 UTC, sdrug submitted a review, later dismissed

2023-03-01 15:26 UTC, aalu1418 approved these changes, later dismissed

2023-03-02 12:35 UTC, sdrug approved these changes

2023-03-02 12:36 UTC, merged