BCI-1259: Add upgradeability tests in hardhat
smartcontractkit/chainlink-starknet pull request #256
Opened 2023-05-08 21:27 UTC by augustbleeds

Note: I had to update the hardhat plugin to accept the ClassHash input arguments. I will create a quick PR to add that to the main branch.

2023-05-09 07:56 UTC, cfal commented on contracts/test/upgradeable.test.ts
> +            // we're not able to directly call bar via hardhat StarknetContract because
you can just do nonUpgradeableFactory.getContractAt() with your contract address to get an updated `StarknetContract` instance

2023-05-09 13:09 UTC, augustbleeds commented on contracts/test/upgradeable.test.ts
> +            // we're not able to directly call bar via hardhat StarknetContract because
Thanks 👍 that's much better haha

2023-05-10 05:56 UTC, cfal reviewed
can you rebase? the changeset should be much easier to see now

2023-05-10 05:56 UTC, cfal commented on contracts/package.json
> +    "@shardlabs/starknet-hardhat-plugin": "git+https://github.com/augustbleeds/starknet-hardhat-plugin#ae53af4",
your PR got merged 🥳 so i pointed the deploy PR to latest tip-of-tree on the spaceshard repo (realized i could have done this before instead of using a fork as well)

so you should be able to remove this change now

2023-05-10 10:46 UTC, cfal commented on contracts/package.json
> +    "@shardlabs/starknet-hardhat-plugin": "git+https://github.com/augustbleeds/starknet-hardhat-plugin#ae53af4",
ah, i remember now that doesn't work because dist isn't automatically built for the plugin like it is for starknetjs

2023-05-10 12:35 UTC, augustbleeds commented on contracts/package.json
> +    "@shardlabs/starknet-hardhat-plugin": "git+https://github.com/augustbleeds/starknet-hardhat-plugin#ae53af4",
Yeah, why is that? It has a yarn build command, so I don't know why npm/yarn doesn't pick that up

2023-05-10 12:35 UTC, augustbleeds commented on contracts/package.json
> +    "@shardlabs/starknet-hardhat-plugin": "git+https://github.com/augustbleeds/starknet-hardhat-plugin#ae53af4",
But cool, I'll rebase on your branch

2023-05-11 04:03 UTC, cfal requested changes

2023-05-11 04:03 UTC, cfal commented on contracts/test/upgradeable.test.ts
> +            await expectInvokeError(
nbd, but there's `expectInvokeErrorMsg` to make sure the error being raised is the expected one.. guessing there's a error code for failure to upgrade

2023-05-11 04:03 UTC, cfal commented on contracts/test/upgradeable.test.ts
> +            const nonExistentClassHash = `0x${starkwareCrypto.pedersen(["random", "hash"])}`
you should be able to use `require('starknet').ec.starkCurve.pedersen` instead of requiring a new dep

2023-05-11 13:47 UTC, closed without merging