bump starknet.go v0.7.2; juno v0.12.0
smartcontractkit/chainlink-starknet pull request #555
Opened 2024-11-26 00:11 UTC by chray-zhang

2024-11-26 14:05 UTC, jmank88 commented on relayer/pkg/starknet/client.go
These had incompatibilities, but they were unused.

2024-11-26 14:06 UTC, jmank88 commented on relayer/pkg/chainlink/txm/txm.go
This type was renamed

2024-11-26 14:07 UTC, jmank88 commented
The txm is constructing a `InvokeTxnV3` but `AddInvokeTransaction` now expects a `rpc.BroadcastInvokeTxnType`

2025-01-15 16:48 UTC, jmank88 submitted a review, later dismissed

2025-01-15 18:36 UTC, augustbleeds approved these changes

2025-01-15 20:11 UTC, augustbleeds requested changes
should integration tests be failing?

2025-01-15 22:27 UTC, ilija42 submitted a review, later dismissed

2025-04-07 14:18 UTC, jmank88 commented on relayer/pkg/chainlink/txm/txm.go
In an earlier version, on the name had changed. Now the field names changed too, and my first attempt has led to nil pointers :facepalm: 
- [ ] use correct `FeeEstimation` fields

2025-04-30 02:18 UTC, jmank88 commented on relayer/pkg/chainlink/txm/txm.go
> +}
Unused?
```suggestion
func fillEmptyFeeEstimation(ctx context.Context, feeEstimation *starknetrpc.FeeEstimation, provider starknetrpc.RpcProvider) {
	if feeEstimation.L1DataGasConsumed.IsZero() {
		// default value for L1DataGasConsumed in most cases
		feeEstimation.L1DataGasConsumed = new(felt.Felt).SetUint64(224)
	}
	if feeEstimation.L1DataGasPrice.IsZero() {
		// getting the L1DataGasPrice from the latest block as reference
		result, _ := provider.BlockWithTxHashes(ctx, starknetrpc.WithBlockTag("latest"))
		block := result.(*starknetrpc.BlockTxHashes)
		feeEstimation.L1DataGasPrice = block.L1DataGasPrice.PriceInFRI
	}
}
```

2025-10-31 00:48 UTC, closed without merging