Renamings to conform .sol interface
smartcontractkit/chainlink-starknet pull request #71
Opened 2022-08-09 12:43 UTC by taco-paco

Change observation_timestamp -> started_at, transmission_timestamp -> updated_at to conform to conform `AggregatorV3Interface` namings

2022-08-10 09:08 UTC, archseer commented
Can you rebase? I merged some changes that should make the tests pass again

2022-08-10 13:08 UTC, taco-paco commented
> Can you rebase? I merged some changes that should make the tests pass again

done

2022-08-11 07:34 UTC, archseer commented
Looks fine to me but it seems to have some commits from develop rebased in?

2022-08-11 07:38 UTC, archseer approved these changes

2022-08-14 19:04 UTC, krebernisak requested changes
I'm not sure what happened with this PR, but it's not clean and includes a lot of changes from L2EP and changes from other branches that are either already closed or still open.

In any case, please clean this up using the following workflow:

- Rebase the renaming PR onto develop (currently on top of L2EP branch), include only the renaming - so we can quickly review and be done with this part.
- If there are specific L2EP changes you added here (not git branching/PR issues) extract those and add them to the opened L2EP PR

At that point we should be able to quickly review and merge.

Thank you!

2022-08-14 19:04 UTC, krebernisak commented on contracts/contracts/mocks/uptime_feed_mock.cairo
> +%lang starknet
Not sure how this file ended up her in this PR, it should be rebased out and included in the L2EP specific PR:

- https://github.com/smartcontractkit/chainlink-starknet/pull/56

2022-08-14 19:04 UTC, krebernisak commented on contracts/contracts/ocr2/SequencerUptimeFeed/library.cairo
> +%lang starknet
Not sure how this file ended up her in this PR, it should be rebased out and included in the L2EP specific PR:

- https://github.com/smartcontractkit/chainlink-starknet/pull/56

2022-08-14 19:04 UTC, krebernisak commented on contracts/contracts/ocr2/SequencerUptimeFeed/sequencer_uptime_feed.cairo
> +%lang starknet
Not sure how this file ended up her in this PR, it should be rebased out and included in the L2EP specific PR:

- https://github.com/smartcontractkit/chainlink-starknet/pull/56

2022-08-14 19:04 UTC, krebernisak commented on contracts/contracts/utils.cairo
> +from starkware.cairo.common.math import assert_in_range
Context: only used in L2EP

Not sure how this file ended up her in this PR, it should be rebased out and included in the L2EP specific PR:

- https://github.com/smartcontractkit/chainlink-starknet/pull/56

2022-08-14 19:04 UTC, krebernisak commented on contracts/test/ocr2/aggregator-test.ts
> +    // console.log(decodedEvents)
Used for local debugging? 

Let's uncomment this and instead `console.log` we assert on data like code below.

2022-08-14 19:04 UTC, krebernisak commented on contracts/test/ocr2/sequencer-uptime-feed.ts
> +import { expect } from 'chai'
Not sure how this file ended up her in this PR, it should be rebased out and included in the L2EP specific PR:

- https://github.com/smartcontractkit/chainlink-starknet/pull/56

2022-08-14 19:04 UTC, krebernisak commented on contracts/test/utils.ts
> +import { expect } from 'chai'
Not sure how this file ended up her in this PR, it should be rebased out and included in the L2EP specific PR:

- https://github.com/smartcontractkit/chainlink-starknet/pull/56

2022-08-14 19:04 UTC, krebernisak commented on shell.nix
> +
This was added by @archseer in another PR, what's happening here!? :)

2022-08-15 09:23 UTC, taco-paco commented
> * If there are specific L2EP changes you added here (not git branching/PR issues) extract those and add them to the opened L2EP PR

It contains changes relevant only in context of l2ep pr that's why I made pr to l2ep branch 
I think I will just cherry-pick initial change to l2ep branch and we will continue discussion there if its required

2022-08-17 06:01 UTC, taco-paco commented on contracts/contracts/mocks/uptime_feed_mock.cairo
> +%lang starknet
[Cherry-picked renaming commit](https://github.com/smartcontractkit/chainlink-starknet/pull/56/commits/947073583a570aa5124202725a46bd1ab07acf12) in main l2 branch

2022-08-17 06:02 UTC, taco-paco commented on contracts/contracts/mocks/uptime_feed_mock.cairo
> +%lang starknet
Closing this pr

2022-08-17 06:02 UTC, closed without merging